language: node_js
dist: focal
node_js:
- '20'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: HpT4scMm7DdtRPISXOVwqlIOsHh68VOyU3OBarwIFkAHsMX7i2LEZWcCjRtCntWxMBl1Ruwq46AewHx6qRw87Pw47S6KHZQLJie1vWY3HdnBVL2EZwgVIuG/RC8JtuDBeSbCtxdAwWIsPD/9t3FqBYfvssn/94j4+S/w404eGpCOQg78kyeD8wLUvlp5Xp5ZRWkdR0F43KNXK+fh+/zpA+3TV0Sg6shQT0eUzzjWbrPfsrmg1S1Gx0wRa6OXXiQeG06pkaumtiSP0Q0ijAeNuVW77jbe27wXuNDm681ZbTlZTn3S4iFQ62zdEgWnp6co8DE53VqVOAjIyzGQ1E7kst3h7/XmNs2DfbhCa8p1a8OPrJVVUku4DyYjk91gRSmY56Fyz3YdHKhMnj4X/x6aVM+IYrbsmPvzX58ijGl8E9G1hx6/DfL3r5VE4G7bhwds80QlywnwNfIAYXAd7hhdTeeuoh710+ZriWJaPwiIjnmlK6y4gb0mw581vXS3wpqAGlwgGBjZgX6y1dwVmZiSTmu5QtfIFMwM0g1jw8L7LgNfFY7hltMxfKvWLQrZVoQJ5ardiq5qvKY1Cyyaeob9UYEBQWXNCYdyQTkf58KxrvxSVt6h+AoyOc8l98NS/il38DTJJQ8G2ek88fLY3cACWSrn5c0C3lJZAMPYmb7ow1M=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
